In [1]:
import cv2  #cv2 is used for image processing

In [2]:
photo= cv2.imread("asphalt_9.jpg")  #reading image and storing in variable i.e. photo

In [3]:
photo #these are the dimention in the photo

array([[[ 34,  15,   2],
        [ 37,  18,   5],
        [ 38,  19,   6],
        ...,
        [ 35,  16,   8],
        [ 35,  16,   8],
        [ 35,  16,   8]],

       [[ 35,  16,   3],
        [ 37,  18,   5],
        [ 38,  19,   6],
        ...,
        [ 35,  16,   8],
        [ 35,  16,   8],
        [ 35,  16,   8]],

       [[ 37,  18,   5],
        [ 37,  18,   5],
        [ 38,  18,   7],
        ...,
        [ 36,  17,   9],
        [ 36,  17,   9],
        [ 36,  17,   9]],

       ...,

       [[ 34,  45,  49],
        [ 34,  45,  49],
        [ 35,  46,  50],
        ...,
        [108, 141, 167],
        [108, 141, 167],
        [107, 140, 166]],

       [[ 34,  45,  49],
        [ 34,  45,  49],
        [ 35,  46,  50],
        ...,
        [105, 138, 164],
        [105, 138, 164],
        [103, 136, 162]],

       [[ 34,  45,  49],
        [ 34,  45,  49],
        [ 35,  46,  50],
        ...,
        [101, 134, 160],
        [100, 132, 161],
        [ 99, 131, 160]]

In [4]:
photo.shape  #this is the shape i.e. the whole dimention for the pic

(503, 800, 3)

In [ ]:
#this will show up the real image (uncropped)
cv2.imshow('Original image',photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
#for cropping 
cphoto= photo[110:420,110:675]

In [ ]:
#this will show up the cropped image
cv2.imshow('Original image',cphoto)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
cphoto.shape

(310, 565, 3)

In [7]:
cphoto

array([[[ 33,  21,  17],
        [ 33,  21,  17],
        [ 29,  18,  14],
        ...,
        [ 79,  67,  63],
        [ 79,  67,  63],
        [ 79,  67,  63]],

       [[ 32,  20,  16],
        [ 32,  20,  16],
        [ 29,  18,  14],
        ...,
        [ 81,  69,  65],
        [ 81,  69,  65],
        [ 81,  69,  65]],

       [[ 33,  18,  15],
        [ 31,  19,  15],
        [ 31,  21,  14],
        ...,
        [ 83,  71,  65],
        [ 83,  71,  65],
        [ 82,  70,  64]],

       ...,

       [[ 86,  90, 101],
        [ 84,  89,  98],
        [ 83,  86,  94],
        ...,
        [213, 221, 228],
        [219, 226, 229],
        [220, 225, 228]],

       [[ 84,  86,  96],
        [ 81,  84,  92],
        [ 78,  84,  91],
        ...,
        [209, 217, 224],
        [213, 222, 226],
        [214, 220, 225]],

       [[ 82,  85,  93],
        [ 80,  83,  91],
        [ 77,  83,  90],
        ...,
        [197, 206, 215],
        [201, 212, 216],
        [201, 211, 218]]

In [8]:
newphoto = cv2.cvtColor( photo ,  cv2.COLOR_BGR2GRAY ) #change the colour of the photo

In [ ]:
#this will show up the Grey Colour image
cv2.imshow('Original image',newphoto)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
B, G ,R = cv2.split(photo) # split the colour of the photo

In [10]:
B

array([[ 34,  37,  38, ...,  35,  35,  35],
       [ 35,  37,  38, ...,  35,  35,  35],
       [ 37,  37,  38, ...,  36,  36,  36],
       ...,
       [ 34,  34,  35, ..., 108, 108, 107],
       [ 34,  34,  35, ..., 105, 105, 103],
       [ 34,  34,  35, ..., 101, 100,  99]], dtype=uint8)

In [11]:
G

array([[ 15,  18,  19, ...,  16,  16,  16],
       [ 16,  18,  19, ...,  16,  16,  16],
       [ 18,  18,  18, ...,  17,  17,  17],
       ...,
       [ 45,  45,  46, ..., 141, 141, 140],
       [ 45,  45,  46, ..., 138, 138, 136],
       [ 45,  45,  46, ..., 134, 132, 131]], dtype=uint8)

In [12]:
R

array([[  2,   5,   6, ...,   8,   8,   8],
       [  3,   5,   6, ...,   8,   8,   8],
       [  5,   5,   7, ...,   9,   9,   9],
       ...,
       [ 49,  49,  50, ..., 167, 167, 166],
       [ 49,  49,  50, ..., 164, 164, 162],
       [ 49,  49,  50, ..., 160, 161, 160]], dtype=uint8)

In [18]:
newpic=cv2.merge([B,B,R]) # you change the intensity of the colour


In [17]:
#this will show up the Grey Colour image
cv2.imshow('Original image',newpic)
cv2.waitKey()
cv2.destroyAllWindows()

In [20]:
R.shape  #R is 2d array

(503, 800)

In [22]:
import numpy as np

In [23]:
zeros = np.zeros((503, 800)) 

In [25]:
type(B)

numpy.ndarray

In [26]:
type(zeros)

numpy.ndarray

In [27]:
B.dtype

dtype('uint8')

In [28]:
zeros.dtype

dtype('float64')

In [29]:
z = zeros.astype('uint8')

In [30]:
zeros.dtype

dtype('float64')

In [33]:
z.shape

(503, 800)

In [31]:
new = cv2.merge( [B, G , z] )

In [32]:
#this will show up what id there is no green  image
cv2.imshow('Original image',new)
cv2.waitKey()
cv2.destroyAllWindows()